export const TEST = 'TEST'
export const CHANGE_LOGIN_STATUS = 'CHANGE_LOGIN_STATUS'
export const CHANGE_LOGIN_STATUS_SUCCESS = 'CHANGE_LOGIN_STATUS_SUCCESS'
export const CHANGE_LOGIN_STATUS_FAILURE = 'CHANGE_LOGIN_STATUS_FAILURE'
export const RESET_LOGIN_STATUS = 'RESET_LOGIN_STATUS'

export const GET_USER_INFO = 'GET_USER_INFO'
export const GET_USER_INFO_SUCCESS = 'GET_USER_INFO_SUCCESS'
export const GET_USER_INFO_FAILURE = 'GET_USER_INFO_FAILURE'
export const RESET_USER_INFO = 'RESET_USER_INFO'

export const GET_POST_ITEMS = 'GET_POST_ITEMS'
export const GET_POST_ITEMS_SUCCESS = 'GET_POST_ITEMS_SUCCESS'
export const GET_POST_ITEMS_FAILURE = 'GET_POST_ITEMS_FAILURE'
export const RESET_POST_ITEMS = 'RESET_POST_ITEMS'

export const GET_CURRENT_USER = 'GET_CURRENT_USER'
export const RESET_CURRENT_USER = 'RESET_CURRENT_USER'

export const UPDATE_USER_INFO = 'UPDATE_USER_INFO'
export const UPDATE_USER_INFO_SUCCESS = 'UPDATE_USER_INFO_SUCCESS'
export const UPDATE_USER_INFO_FAILURE = 'UPDATE_USER_INFO_FAILURE'
export const RESET_UPDATE_USER_INFO = 'RESET_UPDATE_USER_INFO'

export const POST_COMMENT = 'POST_COMMENT'
export const POST_COMMENT_SUCCESS = 'POST_COMMENT_SUCCESS'
export const POST_COMMENT_FAILURE = 'POST_COMMENT_FAILURE'
export const RESET_POST_COMMENT = 'RESET_POST_COMMENT'
